AvanzaBank/astrix

- astrix-remoting/src/main/java/com/avanza/astrix/remoting/client/PartitionedRemoteServiceMethod.java
Partitioned Routing does not work for objects with negative hashCodes.
> Use absolute value to ensure correct handling of negative hashcodes

- astrix-fault-tolerance/src/main/java/com/avanza/astrix/ft/hystrix/AstrixCommandProperties.java
- astrix-fault-tolerance/src/main/java/com/avanza/astrix/ft/hystrix/AstrixThreadPoolProperties.java
By resolving the settings once in the constructor, no garbage strings should be created when Hystrix requests the service config as reported in #44.
> Fix for #44

- astrix-context/src/main/java/com/avanza/astrix/context/AstrixConfigurer.java
- astrix-context/src/test/java/com/avanza/astrix/beans/registry/AstrixServiceRegistryTest.java
- astrix-core/src/main/java/com/avanza/astrix/core/AstrixRouting.java
- src/main/javadoc/overview.html
* Adds unit test for method `AstrixServiceRegistryImpl::deregister` and
`getServiceProviderKey`.
* Before this commit, JaCoCo reports 74% line code-coverage from unit tests on
`AstrixServiceRegistryImpl`. After this commit, line code-coverage is 97%.
* Fixes minor spelling corrections.
> Adds unit test for `AstrixServiceRegistryImpl::deregister`

- astrix-gs/src/main/java/com/avanza/astrix/gs/ClusteredProxyCacheImpl.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsModule.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/SpaceTaskDispatcher.java
* The class `ClusteredProxyCacheImpl` is initialized by the Astrix autowiring framework, as specified in `GsModule`.
* Therefore, the components used in the constructor must be well-defined.
* This commit updates a constructor parameter from `List<>` to the more specific `AstrixTraceProvider` so that the type of peremeter is well-defined.
* Reason for updating is to ensure that the autowired object is not an empty list (which it was before), but always the values defined by the `AstrixTraceProvider`.
> TP-270: Bugfix: Initialize `ClusteredProxyCacheImpl` with known classes

- astrix-gs/src/main/java/com/avanza/astrix/gs/ClusteredProxyCacheImpl.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsModule.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/SpaceTaskDispatcher.java
* The class `ClusteredProxyCacheImpl` is initialized by the Astrix autowiring framework, as specified in `GsModule`.
* Therefore, the components used in the constructor must be well-defined.
* This commit updates a constructor parameter from `List<>` to the more specific `AstrixTraceProvider` so that the type of peremeter is well-defined.
* Reason for updating is to ensure that the autowired object is not an empty list (which it was before), but always the values defined by the `AstrixTraceProvider`.
> TP-270: Bugfix: Initialize `ClusteredProxyCacheImpl` with known classes (gs14)

- astrix-config/pom.xml
- astrix-context/pom.xml
- astrix-context/src/main/java/com/avanza/astrix/context/AstrixConfigurer.java
- astrix-fault-tolerance/pom.xml
- astrix-fault-tolerance/src/main/java/com/avanza/astrix/ft/hystrix/HystrixModule.java
- astrix-fault-tolerance/src/main/resources/META-INF/services/com.avanza.astrix.context.AstrixContextPlugin
- astrix-gs-test-util/src/main/java/com/avanza/astrix/gs/test/util/PartitionedPu.java
- astrix-gs/pom.xml
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsModule.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/localview/GsLocalViewModule.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/remoting/GsRemotingModule.java
- astrix-gs/src/main/resources/META-INF/services/com.avanza.astrix.context.AstrixContextPlugin
- astrix-metrics/pom.xml
- astrix-metrics/src/main/java/com/avanza/astrix/metrics/DropwizardPlugin.java
- astrix-metrics/src/main/resources/META-INF/services/com.avanza.astrix.context.AstrixContextPlugin
- astrix-modules/pom.xml
- astrix-netty-remoting/pom.xml
- astrix-netty-remoting/src/main/java/com/avanza/astrix/netty/NettyRemotingModule.java
- astrix-netty-remoting/src/main/resources/META-INF/services/com.avanza.astrix.context.AstrixContextPlugin
- astrix-remoting/pom.xml
- astrix-remoting/src/main/java/com/avanza/astrix/remoting/client/RemotingClientModule.java
- astrix-remoting/src/main/java/com/avanza/astrix/remoting/server/RemotingServerModule.java
- astrix-remoting/src/main/resources/META-INF/services/com.avanza.astrix.context.AstrixContextPlugin
- astrix-service-registry-pu/src/main/java/com/avanza/astrix/service/registry/pu/SpaceServiceRegistryEntry.java
- astrix-service-registry/pom.xml
- astrix-spring/pom.xml
- astrix-spring/src/main/java/com/avanza/astrix/spring/SpringModule.java
- astrix-spring/src/main/resources/META-INF/services/com.avanza.astrix.context.AstrixContextPlugin
- astrix-versioning/pom.xml
- pom.xml
* Backports changes from the `gs14` branch, in order to support compilation using a java11 jdk.
* Adds explicit exception during startup if the current jre will not support this version of GigaSpaces.
* Reason for backporting changes from the `gs14` branch is to make the diff on that branch smaller, and to make it possible to compile using java11, but still target java8 compatibility.
> TP-349: Allow building on Java11

- astrix-gs-test-util/src/main/java/com/avanza/astrix/gs/test/util/PartitionedPu.java
- astrix-gs-test-util/src/main/java/com/avanza/astrix/gs/test/util/PartitionedPuConfigurer.java
- astrix-gs-test-util/src/main/java/com/avanza/astrix/gs/test/util/SecurityManagerForTests.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/ClusteredProxyCacheImpl.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsBinder.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsComponent.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsModule.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/security/DefaultGsSecurityProvider.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/security/GsSecurityManager.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/security/GsSecurityProvider.java
- astrix-gs/src/main/resources/config/security/security.properties
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/GigaSpacesAuthenticationTest.java
- astrix-integration-tests/src/test/resources/log4j.properties
* Adds `GsSecurityProvider` interface that can be overridden in an Astrix plugin to supply a serverside authenticator and client-side credentials.
* Adds wiring in Astrix so that started PUs will use the security provider if the space has enabled `<os-core:security secured="true" />`.
* Adds class `GsSecurityManager` as an implementation of GigaSpaces server-side `SecurityManager`, which will delegate server-side authentication to the class provided by `GsSecurityProvider`.
> TP-325: Allow Astrix plugins for server- & client authentication

- astrix-gs-test-util/src/main/java/com/avanza/astrix/gs/test/util/PartitionedPu.java
- astrix-gs-test-util/src/main/java/com/avanza/astrix/gs/test/util/PartitionedPuConfigurer.java
- astrix-gs-test-util/src/main/java/com/avanza/astrix/gs/test/util/SecurityManagerForTests.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/ClusteredProxyCacheImpl.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsBinder.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsComponent.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsModule.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/security/DefaultGsSecurityProvider.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/security/GsSecurityManager.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/security/GsSecurityProvider.java
- astrix-gs/src/main/resources/config/security/security.properties
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/GigaSpacesAuthenticationTest.java
- astrix-integration-tests/src/test/resources/log4j.properties
* Adds `GsSecurityProvider` interface that can be overridden in an Astrix plugin to supply a serverside authenticator and client-side credentials.
* Adds wiring in Astrix so that started PUs will use the security provider if the space has enabled `<os-core:security secured="true" />`.
* Adds class `GsSecurityManager` as an implementation of GigaSpaces server-side `SecurityManager`, which will delegate server-side authentication to the class provided by `GsSecurityProvider`.
> TP-325: Allow Astrix plugins for server- & client authentication (GS14)

- astrix-gs/src/main/java/com/avanza/astrix/gs/ClusteredProxyCacheImpl.java
* Allows using a singleton instance of a `CredentialsProvider` via system properties
* The reason for adding it is to make Astrix use the correct credentials during integration tests, instead of an actual implementation.
This MR goes together with https://github.com/AvanzaBank/gs-test/pull/8
> TP-325: Allow singleton CredentialsProvider during GS tests

- astrix-integration-tests/pom.xml
- doc-snippets/pom.xml
- examples/example-application-runners/pom.xml
- examples/lunch-grader-parent/lunch-grader-pu/pom.xml
- examples/lunch-parent/lunch-pu/pom.xml
- examples/lunch-tests/pom.xml
- pom.xml
- tutorial/trading-api-parent/trading-pu/pom.xml
* Replaces the variable (from property) groupname of `gs-test` to an explicit value that is not read from a property.
* Reason for changing is that using a property value for groupname does not seem to work when updating this dependency with `mvn versions:use-latest-versions` (the dependency is not updated).
> TP-431: Use explicit groupname for gs-test

- astrix-integration-tests/pom.xml
- doc-snippets/pom.xml
- examples/example-application-runners/pom.xml
- examples/lunch-grader-parent/lunch-grader-pu/pom.xml
- examples/lunch-parent/lunch-pu/pom.xml
- examples/lunch-tests/pom.xml
- pom.xml
- tutorial/trading-api-parent/trading-pu/pom.xml
Same as #74 , but for gs14 branch.
* Replaces the variable (from property) groupname of `gs-test` to an explicit value that is not read from a property.
* Reason for changing is that using a property value for groupname does not seem to work when updating this dependency with `mvn versions:use-latest-versions` (the dependency is not updated).
> TP-431: Use explicit groupname for gs-test (gs14)

- pom.xml
* `versions-maven-plugin` seems to replace parameterized versions with the explicit version, instead of updating the parameter value.
* Updated versions of `versions-maven-plugin` seem to work correctly (the parameter value is instead updated)
* This reverts commit b457a81513f4e7cd8a8c7e3da77dec8312967cb2.
> Bump `versions-maven-plugin` to `2.8.1`

- pom.xml
* `versions-maven-plugin` seems to replace parameterized versions with the explicit version, instead of updating the parameter value.
* Updated versions of `versions-maven-plugin` seem to work correctly (the parameter value is instead updated)
* This reverts commit 2157d3c484fe5920f098624aebe3d33f85e25f80.
> Bump `versions-maven-plugin` to `2.8.1` (gs14)

- astrix-remoting/src/main/java/com/avanza/astrix/remoting/client/RemotingProxy.java
- astrix-remoting/src/main/java/com/avanza/astrix/remoting/server/AstrixServiceActivatorImpl.java
* Logs all apis provided by Astrix remoting servers
* Logs all apis consumed as Astrix remoting clients
* The intention is the same as for #87 .
Example logging:
Client:
```
[2020-12-14 15:27:37.283] INFO  com.avanza.astrix.remoting.client.RemotingProxy - Initialized Astrix remoting client, consuming api=[com.avanza.astrix.beans.registry.AstrixServiceRegistry] using proxiedApi=[com.avanza.astrix.beans.registry.AstrixServiceRegistry]
[2020-12-14 15:27:37.694] INFO  com.avanza.astrix.remoting.client.RemotingProxy - Initialized Astrix remoting client, consuming api=[se.example.ExternalMessagingService] using proxiedApi=[se.example.ExternalMessagingServiceAsync]
```
Server:
```
[2020-12-14 15:27:15,094] INFO  com.avanza.astrix.remoting.server.AstrixServiceActivatorImpl - Initialized Astrix …
```
> TP-559: Log server and client apis and impls

- astrix-remoting/src/main/java/com/avanza/astrix/remoting/client/RemotingProxy.java
- astrix-remoting/src/main/java/com/avanza/astrix/remoting/server/AstrixServiceActivatorImpl.java
* Same as #88 , but for gs14
* Logs all apis provided by Astrix remoting servers
* Logs all apis consumed as Astrix remoting clients
Example logging:
Client:
```
[2020-12-14 15:27:37.283] INFO  com.avanza.astrix.remoting.client.RemotingProxy - Initialized Astrix remoting client, consuming api=[com.avanza.astrix.beans.registry.AstrixServiceRegistry] using proxiedApi=[com.avanza.astrix.beans.registry.AstrixServiceRegistry]
[2020-12-14 15:27:37.694] INFO  com.avanza.astrix.remoting.client.RemotingProxy - Initialized Astrix remoting client, consuming api=[se.example.ExternalMessagingService] using proxiedApi=[se.example.ExternalMessagingServiceAsync]
```
Server:
```
[2020-12-14 15:27:15,094] INFO  com.avanza.astrix.remoting.server.AstrixServiceActivatorImpl - Initialized Astrix remoting …
```
> TP-559: Log server and client apis and impls (GS14)

- astrix-context/src/main/java/com/avanza/astrix/beans/async/ContextPropagation.java
- astrix-context/src/main/java/com/avanza/astrix/beans/async/ContextPropagator.java
- astrix-context/src/test/java/com/avanza/astrix/beans/async/ContextPropagationTest.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/SpaceTaskDispatcher.java
- astrix-gs/src/main/java/com/avanza/astrix/remoting/util/GsUtil.java
- astrix-gs/src/test/java/com/avanza/astrix/remoting/util/GsUtilTest.java
* Applies all `ContextPropagator`s on async callbacks.
* Reason for applying them is so that if the calling application has defined operations that carry thread state to other threads, we also want to carry along that state to the threads that execute async callbacks.
* In effect, this will make contextpropagation also work on Astrix clients after an async call has completed, when the callback is executed - the context will be propagated also to these callbacks.
> TP-322: Apply contextpropagators on async callbacks

- astrix-context/src/main/java/com/avanza/astrix/beans/async/ContextPropagation.java
- astrix-context/src/main/java/com/avanza/astrix/beans/async/ContextPropagator.java
- astrix-context/src/test/java/com/avanza/astrix/beans/async/ContextPropagationTest.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/SpaceTaskDispatcher.java
- astrix-gs/src/main/java/com/avanza/astrix/remoting/util/GsUtil.java
- astrix-gs/src/test/java/com/avanza/astrix/remoting/util/GsUtilTest.java
Same as #91 , but for `gs14` branch.
* Applies all `ContextPropagator`s on async callbacks.
* Reason for applying them is so that if the calling application has defined operations that carry thread state to other threads, we also want to carry along that state to the threads that execute async callbacks.
* In effect, this will make contextpropagation also work on Astrix clients after an async call has completed, when the callback is executed - the context will be propagated also to these callbacks.
> TP-322: Apply contextpropagators on async callbacks (gs14)

- astrix-context/src/main/java/com/avanza/astrix/beans/async/ContextPropagation.java
- astrix-context/src/main/java/com/avanza/astrix/beans/async/ContextPropagator.java
- astrix-context/src/test/java/com/avanza/astrix/beans/async/ContextPropagationTest.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/SpaceTaskDispatcher.java
- astrix-gs/src/main/java/com/avanza/astrix/remoting/util/GsUtil.java
- astrix-gs/src/test/java/com/avanza/astrix/remoting/util/GsUtilTest.java
Same as #91 , but for `gs14.5` branch.
* Applies all `ContextPropagator`s on async callbacks.
* Reason for applying them is so that if the calling application has defined operations that carry thread state to other threads, we also want to carry along that state to the threads that execute async callbacks.
* In effect, this will make contextpropagation also work on Astrix clients after an async call has completed, when the callback is executed - the context will be propagated also to these callbacks.
> TP-322: Apply contextpropagators on async callbacks (gs14.5)

- astrix-context/src/main/java/com/avanza/astrix/context/AstrixApiProviderClassScanner.java
- astrix-fault-tolerance/pom.xml
- astrix-gs/pom.xml
- astrix-test-support/src/main/java/com/avanza/astrix/test/ServiceInvocationExceptionTestBase.java
- astrix-versioning/pom.xml
- astrix-versioning/src/test/java/com/avanza/astrix/versioning/jackson2/VersionedJsonObjectMapperTest.java
- pom.xml
Update reflections to 0.9.12. Note that this version misbehaves a bit in that it throws an exception when retrieving results from a scan that did not match anything. This is handled by catching the exception and returning empty in our code. The bug was fixed in April 2020 (https://github.com/ronmamo/reflections/commit/9a1ac08d59311a91f3dad06f0c831eccdc47f1e3) but no new version has been released yet.
Remove remaining usages of Guava in tests.
Add dependency to `jsr305` in `astrix-gs`, for `@GuardedBy` annotation. This annotation is not retained at runtime, therefore the dependency is _optional_. An optional dependency is present at compile time but not at runtime.
> Remove Guava

- astrix-context/src/main/java/com/avanza/astrix/beans/registry/InMemoryServiceRegistry.java
- astrix-test-support-common/src/main/java/com/avanza/astrix/test/AstrixTestContext.java
- astrix-test-support-junit4/src/main/java/com/avanza/astrix/test/AstrixRule.java
- astrix-test-support-junit5/src/main/java/com/avanza/astrix/test/AstrixExtension.java
* Updates `InMemoryServiceRegistry` so that it may take a user-supplied instance of `MapConfigSource`, instead of always creating a new config source.
* Updates test rule setup classes to allow sending such a custom `MapConfigSource` when setting up tests.
* Reason for allowing a custom `MapConfigSource` is to make it easier for surrounding frameworks to interoperate with Astrix during test setup.
> TP-772: Allow custom `MapConfigSource` in `InMemoryServiceRegistry`

- astrix-context/src/main/java/com/avanza/astrix/beans/registry/InMemoryServiceRegistry.java
- astrix-test-support-common/src/main/java/com/avanza/astrix/test/AstrixTestContext.java
- astrix-test-support-junit4/src/main/java/com/avanza/astrix/test/AstrixRule.java
* Adds getter for `MapConfigSource` in `AstrixRule`
* This is a continuation of the work to make it easier for surrounding frameworks to interoperate with Astrix during test setup.
> TP-722: Add getters for `MapConfigSource` to `AstrixRule`

- astrix-bom/pom.xml
- pom.xml
* Updates `astrix-bom` so that the versions provided by it only includes astrix components.
* Specifically, with this commit, importing `astrix-bom` in another library does not set the versions that are speciied in this project's parentpom.
* The intention with this commit is, for example, to not specify versions of junit or gigaspaces when importing `astrix-bom`.
Example of the problem before this commit:
```
~/projects/astrix/astrix-bom$ mvn help:effective-pom | fgrep -B 1 -A 3 org.junit  | head -n 5
<dependency>
<groupId>org.junit.jupiter</groupId>
<artifactId>junit-jupiter</artifactId>
<version>5.7.2</version>
</dependency>
```
With this commit:
```
~/projects/astrix/astrix-bom$ mvn help:effective-pom | fgrep org.junit
(no output)
```
> TP-780: Only specify astrix libs in astrix-bom

- astrix-bom/pom.xml
* Prevents the following build errors as seen in jenkins build:
```
$ mvn -B -Prelease enforcer:enforce
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (default-cli) on project astrix-bom: No rules are configured. Use the skip flag if you want to disable execution. -> [Help 1]
```
Follow-up to #112
> TP-780: Add `maven-enforcer-plugin` for `astrix-bom`

- astrix-gs/src/main/java/com/avanza/astrix/gs/remoting/GsRemotingTransport.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/AstrixServiceUnavailableIntegrationTest.java
* Makes `astrix-gs` throw `ServiceUnavailableException` instead of `QuiesceException` when calling an astrix service on a quiesced space.
Please note that this MR is against the `v0.45.x` legacybranch, and not `master`. On `master`, calling an astrix service on a quiesced space does not cause `QuiesceException` but instead gives the following exception:
```
SEVERE [com.gigaspaces.spaceproxy.router.lookup.test-space-2] - Failed to find an active server for partition #1 to execute ExecuteTaskSpaceOperationRequest[task=org.openspaces.core.executor.internal.InternalSpaceTaskWrapper@72829eef](elapsed time: 20004ms)
INFO  com.avanza.astrix.ft.hystrix.FailedServiceInvocationLogger - Aborted command execution: cause=TIMEOUT astrixBean=com.avanza.astrix.integration.tests.domain.api.LunchService …
```
> TP-808: Throw `ServiceUnavailable` on quiesced spaces

- astrix-context/src/main/java/com/avanza/astrix/beans/service/ServiceBeanInstance.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/GsBinder.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/RestartSpaceTest.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/ServiceRegistryPuIntegrationTest.java
- astrix-service-registry-pu/src/main/java/com/avanza/astrix/service/registry/pu/SpaceServiceRegistryEntryRepository.java
* Makes Astrix clients rebind their service beans whenever any of the PUs in the space have restarted.
* Reason for rebinding is to make sure that clients have up-to-date connection details to which hosts that the space resides on, in case any of the server-side PUs have been relocated or restarted.
* However, GS will detect if any instances have moved automatically, but only after an initial failed connection to any such outdated instances - which might result in timeouts. With this commit, the intention is that such timeouts will be less likely.
* Before this change, if any of the PU instances had been relocated, all clients would fail their connections to the previous relocated instance at least once.
* In particular, this commit intends to resolve the case where
* An instance of a PU …
> TP-568: Rebind service beans when PU has restarted

- astrix-context/src/main/java/com/avanza/astrix/beans/service/ServiceBeanInstance.java
- astrix-gs/src/main/java/com/avanza/astrix/gs/ClusteredProxyCacheImpl.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/gs/ClusteredProxyCacheUtil.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/RestartSpaceTest.java
- astrix-modules/src/main/java/com/avanza/astrix/modules/ObjectCache.java
Follow-up to #121 :
* Updates `ClusteredProxyCacheImpl` so that it will recreate gigaspaces connections when the latest start time of any PU has changed.
* In particular, this change intends to address the situation where more than one astrix service binds to the same space url. In such cases, the astrix service beans were previously recreated when any PU restarted, but the gigaspaces connections remained open since the space url did not change.
> TP-568: Invalidate gs connections if PU starttime changes

- astrix-spring/src/main/java/com/avanza/astrix/spring/AstrixFrameworkBean.java
- astrix-spring/src/test/java/com/avanza/astrix/context/AstrixContextTestUtil.java
- astrix-spring/src/test/java/com/avanza/astrix/spring/AstrixFrameworkBeanDynamicConfigTest.java
* Allows astrix to find an instance of `DynamicConfig` not only from the application spring context, but also from its parent context(s).
* Reason for updating is to make it more similar to how bean resolution in spring usually works: if a bean is provided by a parent context, it is usually available to the app in the same way as if it had been present in the application's own context.
* Specifically, this will allow unit tests that define `DynamicConfig` in parent contexts, and specific contexts that reuse it.
> TP-1010: Bugfix: Allow `DynamicConfig` from parent spring ctx

- astrix-remoting/src/main/java/com/avanza/astrix/remoting/client/PartitionedRemoteServiceMethod.java
- astrix-remoting/src/test/java/com/avanza/astrix/remoting/server/AstrixRemotingTest.java
Example:
```java
void insertAll(@AstrixPartitionedRouting(routingMethod = "getIdAsInt") List<GenericEntity<Serializable>> insertMes);
```
> Support ParameterizedType in @AstrixPartitionedRouting (GS16)

- astrix-integration-tests/pom.xml
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/AstrixIntegrationTest.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/GsRemotingTest.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/RestartSpaceTest.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/ServiceRegistryPuIntegrationTest.java
- astrix-integration-tests/src/test/java/com/avanza/astrix/integration/tests/TracingTests.java
- doc-snippets/pom.xml
- examples/example-application-runners/pom.xml
- examples/lunch-grader-parent/lunch-grader-pu/pom.xml
- examples/lunch-parent/lunch-pu/pom.xml
- examples/lunch-tests/pom.xml
- pom.xml
- tutorial/trading-api-parent/trading-pu/pom.xml
Use updated `gs-test` module that uses unicast instead of multicast.
Also, tests are using ZooKeeper based leader selection instead of LUS based.
> TP-687: WIP on using unicast when running tests with gs-test

- examples/lunch-tests/pom.xml
- examples/lunch-web/pom.xml
- pom.xml
Import `spring-boot-dependencies` pom to manage compatible dependencies.
This should make it easier to upgrade dependencies and keep them in sync with other projects.
> Use Spring Boot dependencies
